### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/ods2020#1]
Caro @nelsonmau te ne metto due tra mille:

- https://preview.uideck.com/items/grand/ (download https://onepagelove.com/grand)
- https://startbootstrap.com/previews/creative/ (dowload https://startbootstrap.com/themes/creative/)

Ma ne avrai tanti anche tu.

**Comment by nelsonmau** [comment]
grazie compare :-)

**Comment by nelsonmau** [comment]
direi di usare il primo che è già ben organizzato per eventi
